import time
from plyer import notification

if __name__ == "__main__":
    while True:
        notification.notify(
            title = "Say Jai Mahakal",
            message = "“Whoever becomes Kalyan Swaroop (embodiment of salvation) is called Shiva, the Savior. If you drink all the bitterness served to you, you will become Shankara or Shiva. Om Namah Shivaya. Shivoham. Bholenath. Neelkanth Mahadev.",
            timeout= 10,
            app_icon = "D:\projects\icon1.ico" 
            
        )
        time.sleep(20)
